server:
  port: 8089

spring:
  application:
    name: review-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ReviewDB
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true

