server:
  port: 8090
  servlet:
    session:
      timeout: 1800 # Set session timeout to 30 minutes (1800 seconds)

spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserDB
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true



